package com.dxc.hibernate;

import java.util.Date;

/**
 * RequestItemsId generated by hbm2java
 */
public class RequestItemsId implements java.io.Serializable {

    private int requestItemsId;
    private Integer serviceProviderId;
    private Date methodCallDatetime;
    private Integer status;
    private Integer csruServiceId;
    private Integer requestId;

    public RequestItemsId() {
    }

    public RequestItemsId(int requestItemsId) {
        this.requestItemsId = requestItemsId;
    }

    public RequestItemsId(int requestItemsId, Integer serviceProviderId, Date methodCallDatetime, Integer status,
                          Integer csruServiceId, Integer requestId) {
        this.requestItemsId = requestItemsId;
        this.serviceProviderId = serviceProviderId;
        this.methodCallDatetime = methodCallDatetime;
        this.status = status;
        this.csruServiceId = csruServiceId;
        this.requestId = requestId;
    }

    public int getRequestItemsId() {
        return this.requestItemsId;
    }

    public void setRequestItemsId(int requestItemsId) {
        this.requestItemsId = requestItemsId;
    }

    public Integer getServiceProviderId() {
        return this.serviceProviderId;
    }

    public void setServiceProviderId(Integer serviceProviderId) {
        this.serviceProviderId = serviceProviderId;
    }

    public Date getMethodCallDatetime() {
        return this.methodCallDatetime;
    }

    public void setMethodCallDatetime(Date methodCallDatetime) {
        this.methodCallDatetime = methodCallDatetime;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getCsruServiceId() {
        return this.csruServiceId;
    }

    public void setCsruServiceId(Integer csruServiceId) {
        this.csruServiceId = csruServiceId;
    }

    public Integer getRequestId() {
        return this.requestId;
    }

    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RequestItemsId))
            return false;
        RequestItemsId castOther = (RequestItemsId) other;

        return (this.getRequestItemsId() == castOther.getRequestItemsId())
                && ((this.getServiceProviderId() == castOther.getServiceProviderId())
                || (this.getServiceProviderId() != null && castOther.getServiceProviderId() != null
                && this.getServiceProviderId().equals(castOther.getServiceProviderId())))
                && ((this.getMethodCallDatetime() == castOther.getMethodCallDatetime())
                || (this.getMethodCallDatetime() != null && castOther.getMethodCallDatetime() != null
                && this.getMethodCallDatetime().equals(castOther.getMethodCallDatetime())))
                && ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
                && castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
                && ((this.getCsruServiceId() == castOther.getCsruServiceId())
                || (this.getCsruServiceId() != null && castOther.getCsruServiceId() != null
                && this.getCsruServiceId().equals(castOther.getCsruServiceId())))
                && ((this.getRequestId() == castOther.getRequestId()) || (this.getRequestId() != null
                && castOther.getRequestId() != null && this.getRequestId().equals(castOther.getRequestId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getRequestItemsId();
        result = 37 * result + (getServiceProviderId() == null ? 0 : this.getServiceProviderId().hashCode());
        result = 37 * result + (getMethodCallDatetime() == null ? 0 : this.getMethodCallDatetime().hashCode());
        result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
        result = 37 * result + (getCsruServiceId() == null ? 0 : this.getCsruServiceId().hashCode());
        result = 37 * result + (getRequestId() == null ? 0 : this.getRequestId().hashCode());
        return result;
    }

}
