package com.dxc.hibernate;
// Generated 27-Mar-2020 11:11:50 by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * Response generated by hbm2java
 */
//@SuppressWarnings("serial")
public class Response implements java.io.Serializable {

    private int requestId;
    private String outputDir;
    private Date responseDate;
    private int csruServiceId;

    public Response() {
    }

    public Response(int requestId, int csruServiceId) {
        this.requestId = requestId;
        this.csruServiceId = csruServiceId;
    }

    public Response(int requestId, String outputDir, Date responseDate, int csruServiceId) {
        this.requestId = requestId;
        this.outputDir = outputDir;
        this.responseDate = responseDate;
        this.csruServiceId = csruServiceId;
    }

    public int getRequestId() {
        return this.requestId;
    }

    public void setRequestId(int requestId) {
        this.requestId = requestId;
    }

    public String getOutputDir() {
        return this.outputDir;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
    }

    public Date getResponseDate() {
        return this.responseDate;
    }

    public void setResponseDate(Date responseDate) {
        this.responseDate = responseDate;
    }

    public int getCsruServiceId() {
        return this.csruServiceId;
    }

    public void setCsruServiceId(int csruServiceId) {
        this.csruServiceId = csruServiceId;
    }
    public String toSave(Response resp) {
        StringBuilder sb = new StringBuilder();
        // sb.append("Request_Items_id: ").append(id.getRequestItemsId()).append(" Service_Provider_id: ").append(id.getServiceProviderId()).append(" method_call_datetime: ").append(id.getMethodCallDatetime()).append(" status: ").append(id.getStatus()).append(" CSRU_Service_id ").append(id.getCsruServiceId()).append(" Request_id ").append(id.getRequestItemsId()).append("\n");
        //sb.append("update soapdemo.Request_Items set Service_Provider_id = ").append(id.getServiceProviderId()).append(", method_call_datetime = now()").append(", status = ").append(id.getStatus()).append(", CSRU_Service_id = ").append(id.getCsruServiceId()).append(", Request_id = ").append(id.getRequestItemsId()).append(" where Request_Items_id = ").append(id.getRequestItemsId());
        
        sb.append("insert into soapdemo.Response (request_id,OutputDir,response_date,CSRU_Service_id) VALUES (").append(resp.getRequestId())
        .append(",'").append(resp.getOutputDir())
                .append("',now(),").append(Integer.toString(resp.getCsruServiceId())).append(")");
        

        return sb.toString();
    }

}
